# status line
[[plugins]]
repo = 'bling/vim-airline'

# syntax check
[[plugins]]
repo = 'scrooloose/syntastic'

# comment
[[plugins]]
repo = 'tomtom/tcomment_vim'

# scroll
[[plugins]]
repo = 'yuroyoro/smooth_scroll.vim'

# Git
[[plugins]]
repo = 'tpope/vim-fugitive'

# Golang
[[plugins]]
repo = 'vim-jp/vim-go-extra'

# HTML5
[[plugins]]
repo = 'othree/html5.vim'
