"dein Scripts-----------------------------
if &compatible
  set nocompatible               " Be iMproved
endif

" Required:
set runtimepath+=/Users/rightgo09/.dein.vim/repos/github.com/Shougo/dein.vim

" Required:
call dein#begin('/Users/rightgo09/.dein.vim')

" Let dein manage dein
" Required:
call dein#add('Shougo/dein.vim')

" Add or remove your plugins here:
"call dein#add('Shougo/neosnippet.vim')
"call dein#add('Shougo/neosnippet-snippets')

" You can specify revision/branch/tag.
"call dein#add('Shougo/vimshell', { 'rev': '3787e5' })

call dein#load_toml($HOME . '/dein.toml', {'lazy': 0})
call dein#load_toml($HOME . '/dein.lazy.toml', {'lazy': 1})

" Required:
call dein#end()

" Required:
filetype plugin indent on
syntax enable

" If you want to install not installed plugins on startup.
"if dein#check_install()
"  call dein#install()
"endif

"End dein Scripts-------------------------

source ~/.vimrc.basic
source ~/.vimrc.apperance
source ~/.vimrc.colors
source ~/.vimrc.tab
source ~/.vimrc.search
source ~/.vimrc.util


source ~/vimrc.syntastic

source ~/vimrc.golang
