if &compatible
  set nocompatible
endif

let s:vimrc_home = $HOME . '/dev/src/github.com/rightgo09/dotfiles/vim'

function! s:source_rc(file)
  execute 'source ' . s:vimrc_home . '/' . a:file
endfunction

call s:source_rc('vimrc.dein')
call s:source_rc('vimrc.basic')
call s:source_rc('vimrc.apperance')
call s:source_rc('vimrc.colors')
call s:source_rc('vimrc.tab')
call s:source_rc('vimrc.indent')
call s:source_rc('vimrc.search')
call s:source_rc('vimrc.util')
call s:source_rc('vimrc.auto_ctags')
call s:source_rc('vimrc.syntastic')
call s:source_rc('vimrc.golang')
